export const languages = [
  ["en", "English"], ["es", "Español"], ["pt", "Português"], ["fr", "Français"], ["de", "Deutsch"],
  ["it", "Italiano"], ["ru", "Русский"], ["zh", "中文"], ["ja", "日本語"], ["hi", "हिन्दी"]
] as const;

export type Lang = (typeof languages)[number][0];

type Card = [string, string];
type Step = [string, string];
type ComparisonRow = [string, string, string, string, string];

type DocsCopy = {
  download: string; screenshots: string; search: string; noResults: string;
  startGroup: string; addinsGroup: string; referenceGroup: string;
  official: string; heroTitle: string; heroBody: string;
  stats: [string, string, string];
  nav: string[];
  overviewKicker: string; overviewTitle: string; overviewBody: string; overviewCards: [Card, Card]; backup: string;
  quickKicker: string; quickTitle: string; quickSteps: Step[];
  officeKicker: string; officeTitle: string; officeBody: string; schema: string; path: string; macroNote: string;
  xmlTitle: string; xmlBody: string; xmlTip: string;
  previewKicker: string; previewTitle: string; previewBody: string; previewCards: [Card, Card, Card];
  vbaTitle: string; vbaBody: string; vbaSecurity: string;
  imagesTitle: string; imagesBody: string; previewWord: string;
  addinsKicker: string; addinsTitle: string; addinsBody: string; addinUse: string; excelUse: string; wordUse: string; pptUse: string;
  packagingKicker: string; packagingTitle: string; packagingBody: string; packagingSafety: string;
  comparisonKicker: string; comparisonTitle: string; comparisonBody: string; comparisonRows: ComparisonRow[]; scopeNote: string;
  troubleshootingKicker: string; troubleshootingTitle: string; troubleshootingCards: [Card, Card, Card, Card];
  referenceKicker: string; referenceTitle: string; referenceBody: string; projectFeatures: string; archivedRepo: string; microsoftRibbon: string; releasesSupport: string;
  independent: string;
};

const commonComparison = {
  en: [
    ["Primary focus", "RibbonX + VBA + add-in workflow", "Focused RibbonX editing", "Classic Custom UI editing", ".NET Office solution development"],
    ["Standalone app", "Yes", "Yes", "Yes", "No, requires Visual Studio"],
    ["Office 2007 / 2010+ customUI", "Yes", "Yes", "Yes", "Yes, via Ribbon XML"],
    ["Multi-tab editing", "Yes", "Yes", "Classic workflow", "IDE tabs"],
    ["XML validation", "Yes", "Yes", "Yes", "IDE/XML tooling"],
    ["Generate callback signatures", "Yes", "Yes", "Yes", "Project code"],
    ["Edit VBA modules inside the file", "Integrated", "Not its primary workflow", "Not its primary workflow", "VSTO primarily uses C#/VB.NET"],
    ["Host-aware ribbon preview", "Integrated", "XML/icon focused", "Classic XML editor", "Visual Designer available with limitations"],
    ["imageMso / custom images", "Yes", "Yes", "Yes", "Yes"],
    ["Create .xlam / .dotm / .ppam", "Integrated", "Primarily edits existing files", "Primarily edits existing files", "Different add-in/project model"],
    ["Build Windows installer", "Integrated with Inno Setup 6", "—", "—", "Handled with deployment tooling"],
    ["Best fit when…", "You want RibbonX, VBA and distribution together", "You want a mature focused RibbonX editor", "You maintain a legacy workflow", "You are building a full .NET Office solution"]
  ] as ComparisonRow[],
  es: [
    ["Enfoque", "Flujo RibbonX + VBA + complementos", "Edición RibbonX especializada", "Edición Custom UI clásica", "Desarrollo de soluciones Office .NET"],
    ["Aplicación independiente", "Sí", "Sí", "Sí", "No, requiere Visual Studio"],
    ["Office 2007 / 2010+ customUI", "Sí", "Sí", "Sí", "Sí, mediante Ribbon XML"],
    ["Edición multipestaña", "Sí", "Sí", "Flujo clásico", "Pestañas del IDE"],
    ["Validación XML", "Sí", "Sí", "Sí", "Herramientas del IDE/XML"],
    ["Generar firmas de callbacks", "Sí", "Sí", "Sí", "Código del proyecto"],
    ["Editar módulos VBA dentro del archivo", "Integrado", "No es su flujo principal", "No es su flujo principal", "VSTO usa principalmente C#/VB.NET"],
    ["Vista previa sensible al host", "Integrada", "Centrado en XML/iconos", "Editor XML clásico", "Diseñador visual disponible con límites"],
    ["imageMso / imágenes personalizadas", "Sí", "Sí", "Sí", "Sí"],
    ["Crear .xlam / .dotm / .ppam", "Integrado", "Principalmente edita archivos existentes", "Principalmente edita archivos existentes", "Modelo de complemento distinto"],
    ["Crear instalador Windows", "Integrado con Inno Setup 6", "—", "—", "Se resuelve con herramientas de despliegue"],
    ["Mejor opción cuando…", "Quieres RibbonX, VBA y distribución juntos", "Quieres un editor RibbonX maduro y especializado", "Mantienes un flujo heredado", "Construyes una solución Office .NET completa"]
  ] as ComparisonRow[]
};

export const docsCopy: Record<Lang, DocsCopy> = {
  en: {
    download:"Download", screenshots:"Screenshots", search:"Search documentation…", noResults:"No results", startGroup:"Start here", addinsGroup:"Add-ins", referenceGroup:"Reference",
    official:"Official documentation · v3.2", heroTitle:"From an Office file to RibbonX, VBA and a distributable add-in.", heroBody:"A practical guide to editing customUI XML, working with VBA modules, checking callbacks, using imageMso, creating Excel, Word and PowerPoint add-ins, and packaging them for Windows.",
    stats:["main Office hosts","RibbonX schemas","XML + VBA + distribution workflow"],
    nav:["What Ribbon UI Studio is","Quick start","Office files and schemas","RibbonX XML editor","Preview and diagnostics","VBA modules and callbacks","imageMso and custom images","Create Office add-ins","Package add-ins for Windows","Comparison with existing tools","Troubleshooting","Reference and external resources"],
    overviewKicker:"Overview", overviewTitle:"What Ribbon UI Studio is designed to solve", overviewBody:"Ribbon UI Studio is a Windows desktop application focused on Microsoft Office RibbonX customization. Instead of splitting XML, callbacks, VBA modules, icons and packaging across unrelated tools, it keeps them around the same Office document or add-in.", overviewCards:[["Office file editor","Open the Office Open XML package and work with customUI/customUI14, images and related content without manually editing the ZIP."],["End-to-end workflow","Design the ribbon, check callbacks, edit VBA, create an add-in and prepare its Windows installer from the same product."]], backup:"Always keep a backup before modifying an existing Office document.",
    quickKicker:"Quick start", quickTitle:"Your first customization in six steps", quickSteps:[["Open an Office file","Choose a compatible document or add-in and let the project tree expose its contents."],["Create or open customUI","Choose Office 2007 or Office 2010+ depending on the schema you need."],["Edit XML","Work in Monaco with tabs, formatting and RibbonX templates."],["Validate and preview","Check syntax, IDs, callbacks and images before opening Office."],["Connect VBA","Generate missing callbacks and edit document modules when appropriate."],["Save and test","Write changes back to the Office file and test the ribbon in the host application."]],
    officeKicker:"Office format", officeTitle:"Office 2007 and Office 2010+ use different RibbonX parts", officeBody:"Ribbon UI Studio recognizes both common Open XML package locations and can create the correct part when it does not exist yet.", schema:"Schema", path:"Path", macroNote:"For VBA callbacks, a macro-free file such as .xlsx, .docx or .pptx must first be saved to a macro-enabled format such as .xlsm, .docm or .pptm.",
    xmlTitle:"Edit XML as code, not as a black box", xmlBody:"The editor keeps documents separated and lets you switch between RibbonX XML and VBA modules without mixing their save targets. Built-in templates provide starting points for common ribbons, dynamic menus, galleries and Office-specific workflows.", xmlTip:"Use stable custom IDs and avoid duplicates across controls in the same Ribbon.",
    previewKicker:"Review before Office", previewTitle:"Visual preview and diagnostics", previewBody:"Ribbon UI Studio can build a ribbon representation without launching Office. The preview interprets tabs, groups, controls, imageMso, embedded images and callback presence so problems can be spotted before final testing.", previewCards:[["XML","Checks valid XML and the expected namespace."],["IDs","Helps detect duplicated or inconsistent identifiers."],["Callbacks","Cross-checks callback attributes against available VBA code."]],
    vbaTitle:"Callbacks no longer have to be copied manually", vbaBody:"When the file supports macros, Ribbon UI Studio can read VBA modules, open them as editor documents and save back to the correct module. It can also create missing callback signatures from RibbonX attributes.", vbaSecurity:"VBA project automation depends on access to the VBA object model. If Office blocks it, module editing or generation cannot complete.",
    imagesTitle:"Built-in icons and custom resources", imagesBody:"The imageMso gallery uses Office identifiers to help locate and copy the correct name. You can also work with custom images embedded in the Office package and verify that the preview can resolve them.", previewWord:"Preview",
    addinsKicker:"Creation", addinsTitle:"Create Excel, Word and PowerPoint add-ins", addinsBody:"The creation workflow can prepare the add-in file, a starter ribbon and the RibbonCallbacks module so the project starts from a coherent structure.", addinUse:"Typical use", excelUse:"Excel tools and automation", wordUse:"Document templates and tools", pptUse:"Presentation tools",
    packagingKicker:"Distribution", packagingTitle:"Package Office add-ins for Windows", packagingBody:"The stable v3.2 packaging workflow uses Inno Setup 6 to compile the Windows installer for .xlam, .dotm and .ppam add-ins.", packagingSafety:"When protection or obfuscation is enabled, the workflow works on a temporary copy so the original add-in is not modified.",
    comparisonKicker:"Comparison", comparisonTitle:"How it compares with existing tools", comparisonBody:"These tools do not all target the same problem. Office RibbonX Editor is a strong focused editor; Visual Studio/VSTO is a full development environment; the original Custom UI Editor is a legacy reference. Ribbon UI Studio aims to cover XML + VBA + add-in + distribution in one application.", comparisonRows:commonComparison.en, scopeNote:"This is a scope comparison, not a quality ranking. Each option can be the right choice for a different project.",
    troubleshootingKicker:"Common issues", troubleshootingTitle:"Before assuming the ribbon is broken", troubleshootingCards:[["Callback does not run","Check the exact XML name, confirm the file supports macros and ensure the procedure exists in an accessible standard module."],["Office does not show the ribbon","Validate XML, check the namespace and confirm customUI.xml/customUI14.xml is correctly registered in the package."],["VBA cannot be edited","Office can block programmatic access to the VBA project. Review Trust Center settings and use trusted documents."],["Image does not appear","Distinguish imageMso from custom images. Custom images need the correct relationship and resource inside the Office package."]],
    referenceKicker:"Sources", referenceTitle:"Useful references", referenceBody:"The comparison is based on each project's public documentation and Microsoft's official VSTO documentation.", projectFeatures:"Project and feature list", archivedRepo:"Archived repository", microsoftRibbon:"Designer and Ribbon XML", releasesSupport:"Releases and support", independent:"Independent software for Microsoft Office. Not affiliated with Microsoft."
  },
  es: {
    download:"Descargar", screenshots:"Capturas", search:"Buscar en la documentación…", noResults:"Sin resultados", startGroup:"Empieza aquí", addinsGroup:"Complementos", referenceGroup:"Referencia",
    official:"Documentación oficial · v3.2", heroTitle:"De un archivo Office a RibbonX, VBA y un complemento distribuible.", heroBody:"Una guía práctica para editar customUI XML, trabajar con módulos VBA, revisar callbacks, usar imageMso, crear complementos para Excel, Word y PowerPoint y empaquetarlos para Windows.",
    stats:["hosts Office principales","esquemas RibbonX","flujo XML + VBA + distribución"],
    nav:["Qué es Ribbon UI Studio","Inicio rápido","Archivos Office y esquemas","Editor XML RibbonX","Vista previa y diagnóstico","Módulos VBA y callbacks","imageMso e imágenes personalizadas","Crear complementos de Office","Empaquetar complementos para Windows","Comparación con herramientas existentes","Solución de problemas","Referencia y recursos externos"],
    overviewKicker:"Introducción", overviewTitle:"Qué resuelve Ribbon UI Studio", overviewBody:"Ribbon UI Studio es una aplicación de escritorio para Windows centrada en personalizaciones RibbonX de Microsoft Office. En lugar de separar XML, callbacks, módulos VBA, iconos y empaquetado en herramientas distintas, los reúne alrededor del mismo archivo o complemento de Office.", overviewCards:[["Editor de archivo Office","Abre el paquete Open XML y trabaja con customUI/customUI14, imágenes y contenido relacionado sin manipular el ZIP manualmente."],["Flujo completo","Diseña la cinta, revisa callbacks, edita VBA, crea un complemento y prepara su instalador Windows desde el mismo producto."]], backup:"Haz siempre una copia de seguridad antes de modificar un documento de Office existente.",
    quickKicker:"Inicio rápido", quickTitle:"Tu primera personalización en seis pasos", quickSteps:[["Abre un archivo Office","Selecciona un documento o complemento compatible y deja que el árbol muestre su contenido."],["Crea o abre customUI","Usa Office 2007 u Office 2010+ según el esquema que necesites."],["Edita XML","Trabaja en Monaco con pestañas, formato y plantillas RibbonX."],["Valida y previsualiza","Revisa sintaxis, IDs, callbacks e imágenes antes de abrir Office."],["Conecta VBA","Genera callbacks faltantes y edita los módulos del documento cuando corresponda."],["Guarda y prueba","Guarda en el archivo Office y prueba la cinta en la aplicación host."]],
    officeKicker:"Formato Office", officeTitle:"Office 2007 y Office 2010+ usan partes RibbonX distintas", officeBody:"Ribbon UI Studio reconoce las dos ubicaciones habituales del paquete Open XML y puede crear la parte correcta cuando todavía no existe.", schema:"Esquema", path:"Ruta", macroNote:"Para callbacks VBA, un archivo sin macros como .xlsx, .docx o .pptx debe guardarse primero como .xlsm, .docm o .pptm.",
    xmlTitle:"Edita el XML como código, no como una caja negra", xmlBody:"El editor mantiene documentos separados y permite alternar entre XML RibbonX y módulos VBA sin mezclar sus rutas de guardado. Las plantillas incluidas sirven como punto de partida para cintas, menús dinámicos, galerías y flujos específicos de Office.", xmlTip:"Usa IDs propios y estables; evita duplicarlos entre controles del mismo Ribbon.",
    previewKicker:"Revisión antes de Office", previewTitle:"Vista previa visual y diagnóstico", previewBody:"Ribbon UI Studio puede construir una representación del Ribbon sin ejecutar Office. La vista previa interpreta tabs, groups, controles, imageMso, imágenes embebidas y la presencia de callbacks para mostrar problemas antes de la prueba final.", previewCards:[["XML","Comprueba que el documento sea XML válido y que el namespace corresponda."],["IDs","Ayuda a detectar identificadores duplicados o inconsistentes."],["Callbacks","Contrasta atributos de callback con el código VBA disponible."]],
    vbaTitle:"Los callbacks dejan de ser texto para copiar manualmente", vbaBody:"Cuando el archivo admite macros, Ribbon UI Studio puede leer módulos VBA, abrirlos como documentos del editor y guardar el módulo correcto. También puede crear callbacks que falten a partir de los atributos RibbonX.", vbaSecurity:"La automatización del proyecto VBA depende del acceso al modelo de objetos VBA. Si Office lo bloquea, la edición o generación de módulos no podrá completarse.",
    imagesTitle:"Iconos nativos y recursos personalizados", imagesBody:"La galería imageMso usa identificadores de Office para ayudarte a localizar y copiar el nombre correcto. También puedes trabajar con imágenes personalizadas embebidas en el paquete Office y comprobarlas en la vista previa.", previewWord:"Vista previa",
    addinsKicker:"Creación", addinsTitle:"Genera complementos para Excel, Word y PowerPoint", addinsBody:"El flujo de creación puede preparar el archivo de complemento, un Ribbon inicial y el módulo RibbonCallbacks para empezar con una estructura coherente.", addinUse:"Uso típico", excelUse:"Herramientas y automatización de Excel", wordUse:"Plantillas y herramientas de documentos", pptUse:"Herramientas de presentaciones",
    packagingKicker:"Distribución", packagingTitle:"Empaquetado de complementos para Windows", packagingBody:"El flujo estable de v3.2 utiliza Inno Setup 6 para compilar el instalador Windows de complementos .xlam, .dotm y .ppam.", packagingSafety:"Cuando se activa protección u ofuscación, el proceso trabaja sobre una copia temporal para no modificar el complemento original.",
    comparisonKicker:"Comparativa", comparisonTitle:"Cómo se compara con herramientas existentes", comparisonBody:"No todas estas herramientas intentan resolver el mismo problema. Office RibbonX Editor es un editor especializado; Visual Studio/VSTO es un entorno de desarrollo completo; el Custom UI Editor original es una referencia heredada. Ribbon UI Studio busca cubrir XML + VBA + complemento + distribución en una sola aplicación.", comparisonRows:commonComparison.es, scopeNote:"Es una comparación de alcance, no un ranking de calidad. Cada opción puede ser la mejor según el tipo de proyecto.",
    troubleshootingKicker:"Problemas comunes", troubleshootingTitle:"Antes de pensar que el Ribbon falló", troubleshootingCards:[["El callback no se ejecuta","Comprueba el nombre exacto en XML, que el archivo admita macros y que el procedimiento exista en un módulo estándar accesible."],["Office no muestra la cinta","Valida el XML, revisa el namespace y confirma que customUI.xml/customUI14.xml esté registrado correctamente dentro del paquete."],["No puedo editar VBA","Office puede bloquear el acceso programático al proyecto VBA. Revisa Trust Center y trabaja con documentos de confianza."],["La imagen no aparece","Distingue entre imageMso y una imagen personalizada. Las imágenes custom necesitan relación y recurso dentro del paquete Office."]],
    referenceKicker:"Fuentes", referenceTitle:"Referencias útiles", referenceBody:"La comparación se basa en la documentación pública de cada proyecto y en la documentación oficial de Microsoft para VSTO.", projectFeatures:"Proyecto y características", archivedRepo:"Repositorio archivado", microsoftRibbon:"Designer y Ribbon XML", releasesSupport:"Versiones y soporte", independent:"Software independiente para Microsoft Office. No afiliado con Microsoft."
  },
  pt: {
    download:"Baixar", screenshots:"Capturas", search:"Pesquisar na documentação…", noResults:"Sem resultados", startGroup:"Comece aqui", addinsGroup:"Suplementos", referenceGroup:"Referência",
    official:"Documentação oficial · v3.2", heroTitle:"De um arquivo do Office para RibbonX, VBA e um suplemento distribuível.", heroBody:"Guia prático para editar customUI XML, trabalhar com módulos VBA, verificar callbacks, usar imageMso, criar suplementos do Excel, Word e PowerPoint e empacotá-los para Windows.", stats:["principais hosts do Office","esquemas RibbonX","fluxo XML + VBA + distribuição"],
    nav:["O que é Ribbon UI Studio","Início rápido","Arquivos Office e esquemas","Editor XML RibbonX","Pré-visualização e diagnóstico","Módulos VBA e callbacks","imageMso e imagens personalizadas","Criar suplementos do Office","Empacotar suplementos para Windows","Comparação com ferramentas existentes","Solução de problemas","Referência e recursos externos"],
    overviewKicker:"Visão geral", overviewTitle:"O que o Ribbon UI Studio resolve", overviewBody:"Ribbon UI Studio é um aplicativo Windows focado na personalização RibbonX do Microsoft Office. Em vez de separar XML, callbacks, módulos VBA, ícones e empacotamento em várias ferramentas, mantém tudo em torno do mesmo arquivo ou suplemento.", overviewCards:[["Editor de arquivo Office","Abra o pacote Open XML e trabalhe com customUI/customUI14, imagens e conteúdo relacionado sem editar o ZIP manualmente."],["Fluxo completo","Projete a faixa, verifique callbacks, edite VBA, crie um suplemento e prepare seu instalador Windows no mesmo produto."]], backup:"Mantenha sempre uma cópia de segurança antes de modificar um documento existente.",
    quickKicker:"Início rápido", quickTitle:"Sua primeira personalização em seis passos", quickSteps:[["Abra um arquivo Office","Escolha um documento ou suplemento compatível."],["Crie ou abra customUI","Use Office 2007 ou Office 2010+ conforme o esquema necessário."],["Edite XML","Trabalhe no Monaco com abas, formatação e modelos RibbonX."],["Valide e visualize","Revise sintaxe, IDs, callbacks e imagens antes de abrir o Office."],["Conecte VBA","Gere callbacks ausentes e edite módulos quando necessário."],["Salve e teste","Grave as alterações no arquivo Office e teste no aplicativo host."]],
    officeKicker:"Formato Office", officeTitle:"Office 2007 e Office 2010+ usam partes RibbonX diferentes", officeBody:"Ribbon UI Studio reconhece as duas localizações comuns do pacote Open XML e pode criar a parte correta.", schema:"Esquema", path:"Caminho", macroNote:"Para callbacks VBA, .xlsx, .docx e .pptx devem ser salvos primeiro como .xlsm, .docm ou .pptm.",
    xmlTitle:"Edite XML como código, não como uma caixa-preta", xmlBody:"O editor mantém documentos separados e permite alternar entre RibbonX XML e módulos VBA sem misturar destinos de gravação. Os modelos incluídos ajudam a iniciar faixas, menus dinâmicos e galerias.", xmlTip:"Use IDs próprios e estáveis e evite duplicações.",
    previewKicker:"Revisão antes do Office", previewTitle:"Pré-visualização e diagnóstico", previewBody:"Ribbon UI Studio pode representar a faixa sem iniciar o Office e interpretar abas, grupos, controles, imageMso, imagens incorporadas e callbacks.", previewCards:[["XML","Verifica XML válido e namespace esperado."],["IDs","Ajuda a detectar identificadores duplicados ou inconsistentes."],["Callbacks","Compara atributos de callback com o código VBA disponível."]],
    vbaTitle:"Callbacks sem cópia manual", vbaBody:"Quando o arquivo aceita macros, o programa pode ler, abrir e salvar módulos VBA e gerar assinaturas de callbacks ausentes a partir do RibbonX.", vbaSecurity:"A automação VBA depende do acesso ao modelo de objetos do projeto VBA. Se o Office bloquear, a edição ou geração não poderá ser concluída.",
    imagesTitle:"Ícones nativos e recursos personalizados", imagesBody:"A galeria imageMso ajuda a localizar o identificador correto e também permite trabalhar com imagens personalizadas incorporadas no pacote Office.", previewWord:"Pré-visualização",
    addinsKicker:"Criação", addinsTitle:"Crie suplementos para Excel, Word e PowerPoint", addinsBody:"O fluxo pode preparar o arquivo do suplemento, uma faixa inicial e o módulo RibbonCallbacks.", addinUse:"Uso típico", excelUse:"Ferramentas e automação do Excel", wordUse:"Modelos e ferramentas de documentos", pptUse:"Ferramentas de apresentações",
    packagingKicker:"Distribuição", packagingTitle:"Empacotar suplementos para Windows", packagingBody:"O fluxo estável da v3.2 usa Inno Setup 6 para compilar o instalador Windows de .xlam, .dotm e .ppam.", packagingSafety:"Proteção ou ofuscação é aplicada a uma cópia temporária para preservar o suplemento original.",
    comparisonKicker:"Comparação", comparisonTitle:"Comparação com ferramentas existentes", comparisonBody:"Office RibbonX Editor é um editor especializado; Visual Studio/VSTO é um ambiente completo; o Custom UI Editor original é uma referência legada. Ribbon UI Studio busca unir XML + VBA + suplemento + distribuição.", comparisonRows:commonComparison.en, scopeNote:"É uma comparação de escopo, não um ranking de qualidade.",
    troubleshootingKicker:"Problemas comuns", troubleshootingTitle:"Antes de concluir que a faixa falhou", troubleshootingCards:[["Callback não executa","Verifique o nome no XML, o suporte a macros e o módulo VBA."],["Office não mostra a faixa","Valide o XML, o namespace e o registro de customUI no pacote."],["Não é possível editar VBA","Revise as configurações de Trust Center e use documentos confiáveis."],["Imagem não aparece","Diferencie imageMso de imagens personalizadas e verifique relações e recursos."]],
    referenceKicker:"Fontes", referenceTitle:"Referências úteis", referenceBody:"A comparação usa documentação pública dos projetos e documentação oficial da Microsoft para VSTO.", projectFeatures:"Projeto e recursos", archivedRepo:"Repositório arquivado", microsoftRibbon:"Designer e Ribbon XML", releasesSupport:"Versões e suporte", independent:"Software independente para Microsoft Office. Não afiliado à Microsoft."
  },
  fr: {
    download:"Télécharger", screenshots:"Captures", search:"Rechercher dans la documentation…", noResults:"Aucun résultat", startGroup:"Bien démarrer", addinsGroup:"Compléments", referenceGroup:"Référence",
    official:"Documentation officielle · v3.2", heroTitle:"D’un fichier Office à RibbonX, VBA et un complément distribuable.", heroBody:"Guide pratique pour modifier customUI XML, travailler avec les modules VBA, vérifier les callbacks, utiliser imageMso, créer des compléments Excel, Word et PowerPoint et les empaqueter pour Windows.", stats:["hôtes Office principaux","schémas RibbonX","flux XML + VBA + distribution"],
    nav:["Qu’est-ce que Ribbon UI Studio","Démarrage rapide","Fichiers Office et schémas","Éditeur XML RibbonX","Aperçu et diagnostic","Modules VBA et callbacks","imageMso et images personnalisées","Créer des compléments Office","Empaqueter pour Windows","Comparaison avec les outils existants","Dépannage","Références et ressources"],
    overviewKicker:"Présentation", overviewTitle:"Ce que Ribbon UI Studio cherche à résoudre", overviewBody:"Ribbon UI Studio est une application Windows dédiée à la personnalisation RibbonX de Microsoft Office. XML, callbacks, modules VBA, icônes et empaquetage restent réunis autour du même document ou complément.", overviewCards:[["Éditeur de fichier Office","Ouvrez le package Open XML et travaillez avec customUI/customUI14, les images et les ressources associées sans éditer le ZIP manuellement."],["Flux de bout en bout","Concevez le ruban, vérifiez les callbacks, éditez VBA, créez un complément et préparez son installateur Windows."]], backup:"Conservez toujours une sauvegarde avant de modifier un document Office existant.",
    quickKicker:"Démarrage rapide", quickTitle:"Votre première personnalisation en six étapes", quickSteps:[["Ouvrir un fichier Office","Choisissez un document ou complément compatible."],["Créer ou ouvrir customUI","Choisissez Office 2007 ou Office 2010+ selon le schéma."],["Modifier le XML","Utilisez Monaco, les onglets, le formatage et les modèles RibbonX."],["Valider et prévisualiser","Contrôlez la syntaxe, les IDs, callbacks et images."],["Connecter VBA","Générez les callbacks manquants et éditez les modules."],["Enregistrer et tester","Enregistrez dans le fichier Office et testez dans l’application hôte."]],
    officeKicker:"Format Office", officeTitle:"Office 2007 et Office 2010+ utilisent des parties RibbonX différentes", officeBody:"Ribbon UI Studio reconnaît les deux emplacements Open XML habituels et peut créer la partie correcte.", schema:"Schéma", path:"Chemin", macroNote:"Pour les callbacks VBA, .xlsx, .docx et .pptx doivent d’abord être enregistrés en .xlsm, .docm ou .pptm.",
    xmlTitle:"Modifiez le XML comme du code", xmlBody:"L’éditeur sépare les documents et permet de passer du XML RibbonX aux modules VBA sans mélanger leurs destinations d’enregistrement. Les modèles intégrés accélèrent les rubans, menus dynamiques et galeries.", xmlTip:"Utilisez des IDs stables et évitez les doublons.",
    previewKicker:"Contrôle avant Office", previewTitle:"Aperçu visuel et diagnostic", previewBody:"Ribbon UI Studio peut représenter le ruban sans lancer Office et interpréter onglets, groupes, contrôles, imageMso, images intégrées et callbacks.", previewCards:[["XML","Vérifie la validité XML et le namespace attendu."],["IDs","Aide à détecter les identifiants dupliqués ou incohérents."],["Callbacks","Compare les attributs de callback avec le code VBA disponible."]],
    vbaTitle:"Des callbacks sans copie manuelle", vbaBody:"Pour les fichiers prenant en charge les macros, le programme peut lire, ouvrir et enregistrer les modules VBA et générer les signatures manquantes depuis RibbonX.", vbaSecurity:"L’automatisation VBA dépend de l’accès au modèle d’objets du projet VBA. Si Office le bloque, l’édition ne peut pas aboutir.",
    imagesTitle:"Icônes natives et ressources personnalisées", imagesBody:"La galerie imageMso aide à trouver le bon identifiant et prend aussi en charge les images personnalisées intégrées au package Office.", previewWord:"Aperçu",
    addinsKicker:"Création", addinsTitle:"Créer des compléments Excel, Word et PowerPoint", addinsBody:"Le flux peut préparer le fichier du complément, un ruban initial et le module RibbonCallbacks.", addinUse:"Usage typique", excelUse:"Outils et automatisation Excel", wordUse:"Modèles et outils de documents", pptUse:"Outils de présentation",
    packagingKicker:"Distribution", packagingTitle:"Empaqueter les compléments pour Windows", packagingBody:"Le flux stable de la v3.2 utilise Inno Setup 6 pour compiler l’installateur Windows des fichiers .xlam, .dotm et .ppam.", packagingSafety:"La protection ou l’obfuscation travaille sur une copie temporaire afin de préserver le complément original.",
    comparisonKicker:"Comparaison", comparisonTitle:"Comparaison avec les outils existants", comparisonBody:"Office RibbonX Editor est un éditeur spécialisé ; Visual Studio/VSTO est un environnement complet ; le Custom UI Editor original est une référence historique. Ribbon UI Studio réunit XML + VBA + complément + distribution.", comparisonRows:commonComparison.en, scopeNote:"Comparaison de périmètre, pas classement de qualité.",
    troubleshootingKicker:"Problèmes fréquents", troubleshootingTitle:"Avant de conclure que le ruban est défaillant", troubleshootingCards:[["Le callback ne s’exécute pas","Vérifiez le nom XML, le format macro et le module VBA."],["Office n’affiche pas le ruban","Validez le XML, le namespace et l’enregistrement de customUI."],["Impossible d’éditer VBA","Vérifiez le Centre de gestion de la confidentialité et utilisez des documents fiables."],["L’image n’apparaît pas","Distinguez imageMso des images personnalisées et contrôlez leurs relations."]],
    referenceKicker:"Sources", referenceTitle:"Références utiles", referenceBody:"La comparaison s’appuie sur la documentation publique des projets et la documentation officielle Microsoft sur VSTO.", projectFeatures:"Projet et fonctionnalités", archivedRepo:"Dépôt archivé", microsoftRibbon:"Designer et Ribbon XML", releasesSupport:"Versions et support", independent:"Logiciel indépendant pour Microsoft Office. Non affilié à Microsoft."
  },
  de: {
    download:"Download", screenshots:"Screenshots", search:"Dokumentation durchsuchen…", noResults:"Keine Ergebnisse", startGroup:"Erste Schritte", addinsGroup:"Add-ins", referenceGroup:"Referenz",
    official:"Offizielle Dokumentation · v3.2", heroTitle:"Von der Office-Datei zu RibbonX, VBA und einem verteilbaren Add-in.", heroBody:"Praxisleitfaden für customUI XML, VBA-Module, Callbacks, imageMso, Excel-/Word-/PowerPoint-Add-ins und deren Windows-Paketierung.", stats:["wichtige Office-Hosts","RibbonX-Schemas","XML + VBA + Distribution"],
    nav:["Was Ribbon UI Studio ist","Schnellstart","Office-Dateien und Schemas","RibbonX XML-Editor","Vorschau und Diagnose","VBA-Module und Callbacks","imageMso und eigene Bilder","Office-Add-ins erstellen","Add-ins für Windows paketieren","Vergleich mit vorhandenen Tools","Fehlerbehebung","Referenzen und Ressourcen"],
    overviewKicker:"Überblick", overviewTitle:"Welches Problem Ribbon UI Studio löst", overviewBody:"Ribbon UI Studio ist eine Windows-Anwendung für Microsoft-Office-RibbonX-Anpassungen. XML, Callbacks, VBA-Module, Symbole und Paketierung bleiben rund um dieselbe Office-Datei oder dasselbe Add-in zusammen.", overviewCards:[["Office-Dateieditor","Öffnen Sie das Open-XML-Paket und bearbeiten Sie customUI/customUI14, Bilder und zugehörige Inhalte ohne manuelle ZIP-Bearbeitung."],["Durchgängiger Workflow","Ribbon entwerfen, Callbacks prüfen, VBA bearbeiten, Add-in erstellen und Windows-Installer vorbereiten."]], backup:"Erstellen Sie vor Änderungen an bestehenden Office-Dokumenten immer eine Sicherung.",
    quickKicker:"Schnellstart", quickTitle:"Die erste Anpassung in sechs Schritten", quickSteps:[["Office-Datei öffnen","Wählen Sie ein kompatibles Dokument oder Add-in."],["customUI erstellen oder öffnen","Wählen Sie Office 2007 oder Office 2010+ je nach Schema."],["XML bearbeiten","Nutzen Sie Monaco, Tabs, Formatierung und RibbonX-Vorlagen."],["Validieren und Vorschau","Prüfen Sie Syntax, IDs, Callbacks und Bilder."],["VBA verbinden","Erzeugen Sie fehlende Callbacks und bearbeiten Sie Module."],["Speichern und testen","Speichern Sie in der Office-Datei und testen Sie im Host."]],
    officeKicker:"Office-Format", officeTitle:"Office 2007 und Office 2010+ verwenden unterschiedliche RibbonX-Teile", officeBody:"Ribbon UI Studio erkennt beide üblichen Open-XML-Pfade und kann den richtigen Teil anlegen.", schema:"Schema", path:"Pfad", macroNote:"Für VBA-Callbacks müssen .xlsx, .docx und .pptx zunächst als .xlsm, .docm oder .pptm gespeichert werden.",
    xmlTitle:"XML als Code bearbeiten", xmlBody:"Der Editor hält Dokumente getrennt und ermöglicht den Wechsel zwischen RibbonX XML und VBA-Modulen, ohne Speicherziele zu vermischen. Vorlagen beschleunigen typische Ribbons, dynamische Menüs und Galerien.", xmlTip:"Verwenden Sie stabile eigene IDs und vermeiden Sie Duplikate.",
    previewKicker:"Prüfung vor Office", previewTitle:"Visuelle Vorschau und Diagnose", previewBody:"Ribbon UI Studio kann das Ribbon ohne Start von Office darstellen und Tabs, Gruppen, Steuerelemente, imageMso, eingebettete Bilder und Callbacks interpretieren.", previewCards:[["XML","Prüft gültiges XML und den erwarteten Namespace."],["IDs","Hilft, doppelte oder inkonsistente IDs zu finden."],["Callbacks","Vergleicht Callback-Attribute mit verfügbarem VBA-Code."]],
    vbaTitle:"Callbacks ohne manuelles Kopieren", vbaBody:"Bei makrofähigen Dateien kann das Programm VBA-Module lesen, öffnen und speichern sowie fehlende Callback-Signaturen aus RibbonX erzeugen.", vbaSecurity:"Die VBA-Automatisierung benötigt Zugriff auf das VBA-Projektobjektmodell. Wird dieser durch Office blockiert, ist die Bearbeitung nicht möglich.",
    imagesTitle:"Office-Symbole und eigene Ressourcen", imagesBody:"Die imageMso-Galerie hilft beim Finden der richtigen Office-ID und unterstützt außerdem eingebettete eigene Bilder.", previewWord:"Vorschau",
    addinsKicker:"Erstellung", addinsTitle:"Excel-, Word- und PowerPoint-Add-ins erstellen", addinsBody:"Der Workflow kann Add-in-Datei, Start-Ribbon und RibbonCallbacks-Modul vorbereiten.", addinUse:"Typischer Einsatz", excelUse:"Excel-Werkzeuge und Automatisierung", wordUse:"Dokumentvorlagen und Werkzeuge", pptUse:"Präsentationswerkzeuge",
    packagingKicker:"Distribution", packagingTitle:"Office-Add-ins für Windows paketieren", packagingBody:"Der stabile v3.2-Workflow verwendet Inno Setup 6 zum Erstellen des Windows-Installers für .xlam, .dotm und .ppam.", packagingSafety:"Schutz oder Obfuskation arbeitet auf einer temporären Kopie, damit das Original unverändert bleibt.",
    comparisonKicker:"Vergleich", comparisonTitle:"Vergleich mit vorhandenen Werkzeugen", comparisonBody:"Office RibbonX Editor ist ein fokussierter Editor; Visual Studio/VSTO eine vollständige Entwicklungsumgebung; der ursprüngliche Custom UI Editor ist eine ältere Referenz. Ribbon UI Studio verbindet XML + VBA + Add-in + Distribution.", comparisonRows:commonComparison.en, scopeNote:"Dies ist ein Funktionsumfang-Vergleich, kein Qualitätsranking.",
    troubleshootingKicker:"Häufige Probleme", troubleshootingTitle:"Bevor Sie von einem Ribbon-Fehler ausgehen", troubleshootingCards:[["Callback startet nicht","Prüfen Sie XML-Namen, Makroformat und VBA-Modul."],["Office zeigt das Ribbon nicht","Validieren Sie XML, Namespace und customUI-Registrierung."],["VBA kann nicht bearbeitet werden","Prüfen Sie Trust Center und verwenden Sie vertrauenswürdige Dokumente."],["Bild fehlt","Unterscheiden Sie imageMso und eigene Bilder und prüfen Sie Beziehungen und Ressourcen."]],
    referenceKicker:"Quellen", referenceTitle:"Nützliche Referenzen", referenceBody:"Der Vergleich basiert auf öffentlicher Projektdokumentation und Microsofts offizieller VSTO-Dokumentation.", projectFeatures:"Projekt und Funktionen", archivedRepo:"Archiviertes Repository", microsoftRibbon:"Designer und Ribbon XML", releasesSupport:"Versionen und Support", independent:"Unabhängige Software für Microsoft Office. Nicht mit Microsoft verbunden."
  },
  it: {
    download:"Scarica", screenshots:"Schermate", search:"Cerca nella documentazione…", noResults:"Nessun risultato", startGroup:"Inizia qui", addinsGroup:"Componenti aggiuntivi", referenceGroup:"Riferimenti",
    official:"Documentazione ufficiale · v3.2", heroTitle:"Da un file Office a RibbonX, VBA e un componente aggiuntivo distribuibile.", heroBody:"Guida pratica per modificare customUI XML, lavorare con moduli VBA, controllare callback, usare imageMso, creare componenti aggiuntivi Excel, Word e PowerPoint e distribuirli su Windows.", stats:["host Office principali","schemi RibbonX","flusso XML + VBA + distribuzione"],
    nav:["Cos’è Ribbon UI Studio","Avvio rapido","File Office e schemi","Editor XML RibbonX","Anteprima e diagnostica","Moduli VBA e callback","imageMso e immagini personalizzate","Creare componenti aggiuntivi Office","Creare installer Windows","Confronto con strumenti esistenti","Risoluzione problemi","Riferimenti e risorse"],
    overviewKicker:"Panoramica", overviewTitle:"Cosa risolve Ribbon UI Studio", overviewBody:"Ribbon UI Studio è un’app Windows dedicata alla personalizzazione RibbonX di Microsoft Office. XML, callback, moduli VBA, icone e packaging restano uniti attorno allo stesso documento o add-in.", overviewCards:[["Editor file Office","Apri il pacchetto Open XML e lavora con customUI/customUI14, immagini e risorse senza modificare manualmente lo ZIP."],["Flusso completo","Progetta il Ribbon, controlla i callback, modifica VBA, crea l’add-in e prepara l’installer Windows."]], backup:"Conserva sempre una copia di backup prima di modificare un documento Office esistente.",
    quickKicker:"Avvio rapido", quickTitle:"La prima personalizzazione in sei passaggi", quickSteps:[["Apri un file Office","Scegli un documento o add-in compatibile."],["Crea o apri customUI","Scegli Office 2007 o Office 2010+ in base allo schema."],["Modifica XML","Usa Monaco, schede, formattazione e modelli RibbonX."],["Valida e visualizza","Controlla sintassi, ID, callback e immagini."],["Collega VBA","Genera callback mancanti e modifica i moduli."],["Salva e prova","Salva nel file Office e prova nell’app host."]],
    officeKicker:"Formato Office", officeTitle:"Office 2007 e Office 2010+ usano parti RibbonX diverse", officeBody:"Ribbon UI Studio riconosce entrambe le posizioni Open XML e può creare la parte corretta.", schema:"Schema", path:"Percorso", macroNote:"Per i callback VBA, .xlsx, .docx e .pptx devono prima essere salvati come .xlsm, .docm o .pptm.",
    xmlTitle:"Modifica XML come codice", xmlBody:"L’editor mantiene i documenti separati e consente di passare da RibbonX XML ai moduli VBA senza confondere i percorsi di salvataggio. I modelli inclusi accelerano ribbon, menu dinamici e gallerie.", xmlTip:"Usa ID personalizzati stabili ed evita duplicati.",
    previewKicker:"Controllo prima di Office", previewTitle:"Anteprima visiva e diagnostica", previewBody:"Ribbon UI Studio può rappresentare il Ribbon senza avviare Office e interpretare schede, gruppi, controlli, imageMso, immagini incorporate e callback.", previewCards:[["XML","Controlla XML valido e namespace previsto."],["ID","Aiuta a rilevare identificatori duplicati o incoerenti."],["Callback","Confronta gli attributi callback con il codice VBA disponibile."]],
    vbaTitle:"Callback senza copia manuale", vbaBody:"Con file abilitati alle macro, il programma può leggere, aprire e salvare moduli VBA e generare firme callback mancanti da RibbonX.", vbaSecurity:"L’automazione VBA richiede accesso al modello a oggetti del progetto VBA. Se Office lo blocca, la modifica non può completarsi.",
    imagesTitle:"Icone native e risorse personalizzate", imagesBody:"La galleria imageMso aiuta a trovare l’identificatore Office corretto e supporta anche immagini personalizzate incorporate.", previewWord:"Anteprima",
    addinsKicker:"Creazione", addinsTitle:"Crea componenti aggiuntivi Excel, Word e PowerPoint", addinsBody:"Il flusso può preparare file add-in, Ribbon iniziale e modulo RibbonCallbacks.", addinUse:"Uso tipico", excelUse:"Strumenti e automazione Excel", wordUse:"Modelli e strumenti per documenti", pptUse:"Strumenti per presentazioni",
    packagingKicker:"Distribuzione", packagingTitle:"Crea installer Windows per gli add-in", packagingBody:"Il flusso stabile v3.2 usa Inno Setup 6 per compilare l’installer Windows di .xlam, .dotm e .ppam.", packagingSafety:"Protezione o offuscamento opera su una copia temporanea, preservando l’add-in originale.",
    comparisonKicker:"Confronto", comparisonTitle:"Confronto con gli strumenti esistenti", comparisonBody:"Office RibbonX Editor è un editor specializzato; Visual Studio/VSTO è un ambiente completo; il Custom UI Editor originale è un riferimento legacy. Ribbon UI Studio unisce XML + VBA + add-in + distribuzione.", comparisonRows:commonComparison.en, scopeNote:"È un confronto di ambito, non una classifica di qualità.",
    troubleshootingKicker:"Problemi comuni", troubleshootingTitle:"Prima di pensare che il Ribbon non funzioni", troubleshootingCards:[["Il callback non parte","Controlla nome XML, supporto macro e modulo VBA."],["Office non mostra il Ribbon","Valida XML, namespace e registrazione customUI."],["VBA non modificabile","Controlla Trust Center e usa documenti attendibili."],["Immagine assente","Distingui imageMso dalle immagini personalizzate e verifica relazioni e risorse."]],
    referenceKicker:"Fonti", referenceTitle:"Riferimenti utili", referenceBody:"Il confronto usa documentazione pubblica dei progetti e documentazione ufficiale Microsoft su VSTO.", projectFeatures:"Progetto e funzionalità", archivedRepo:"Repository archiviato", microsoftRibbon:"Designer e Ribbon XML", releasesSupport:"Versioni e supporto", independent:"Software indipendente per Microsoft Office. Non affiliato a Microsoft."
  },
  ru: {
    download:"Скачать", screenshots:"Скриншоты", search:"Поиск по документации…", noResults:"Ничего не найдено", startGroup:"Начало", addinsGroup:"Надстройки", referenceGroup:"Справка",
    official:"Официальная документация · v3.2", heroTitle:"От файла Office к RibbonX, VBA и распространяемой надстройке.", heroBody:"Практическое руководство по customUI XML, модулям VBA, callback-процедурам, imageMso, созданию надстроек Excel, Word и PowerPoint и их упаковке для Windows.", stats:["основных приложения Office","схемы RibbonX","XML + VBA + распространение"],
    nav:["Что такое Ribbon UI Studio","Быстрый старт","Файлы Office и схемы","Редактор RibbonX XML","Предпросмотр и диагностика","Модули VBA и callbacks","imageMso и свои изображения","Создание надстроек Office","Упаковка для Windows","Сравнение с другими инструментами","Устранение неполадок","Ссылки и ресурсы"],
    overviewKicker:"Обзор", overviewTitle:"Какие задачи решает Ribbon UI Studio", overviewBody:"Ribbon UI Studio — приложение Windows для настройки RibbonX в Microsoft Office. XML, callbacks, модули VBA, значки и упаковка собраны вокруг одного документа или надстройки.", overviewCards:[["Редактор файлов Office","Работайте с customUI/customUI14, изображениями и связанными ресурсами пакета Open XML без ручного редактирования ZIP."],["Полный рабочий процесс","Проектируйте Ribbon, проверяйте callbacks, редактируйте VBA, создавайте надстройку и готовьте Windows-установщик."]], backup:"Всегда сохраняйте резервную копию перед изменением существующего документа Office.",
    quickKicker:"Быстрый старт", quickTitle:"Первая настройка за шесть шагов", quickSteps:[["Откройте файл Office","Выберите совместимый документ или надстройку."],["Создайте или откройте customUI","Выберите схему Office 2007 или Office 2010+."],["Редактируйте XML","Используйте Monaco, вкладки, форматирование и шаблоны RibbonX."],["Проверьте и просмотрите","Проверьте синтаксис, IDs, callbacks и изображения."],["Подключите VBA","Создайте отсутствующие callbacks и отредактируйте модули."],["Сохраните и проверьте","Запишите изменения и протестируйте в приложении Office."]],
    officeKicker:"Формат Office", officeTitle:"Office 2007 и Office 2010+ используют разные части RibbonX", officeBody:"Ribbon UI Studio распознаёт оба стандартных пути Open XML и может создать нужную часть.", schema:"Схема", path:"Путь", macroNote:"Для VBA callbacks файлы .xlsx, .docx и .pptx нужно сначала сохранить как .xlsm, .docm или .pptm.",
    xmlTitle:"Редактируйте XML как код", xmlBody:"Редактор разделяет RibbonX XML и модули VBA, не смешивая места сохранения. Встроенные шаблоны ускоряют создание лент, динамических меню и галерей.", xmlTip:"Используйте стабильные собственные IDs и избегайте дубликатов.",
    previewKicker:"Проверка до запуска Office", previewTitle:"Визуальный предпросмотр и диагностика", previewBody:"Ribbon UI Studio может показать Ribbon без запуска Office и разобрать вкладки, группы, элементы управления, imageMso, встроенные изображения и callbacks.", previewCards:[["XML","Проверяет корректность XML и namespace."],["IDs","Помогает находить дубликаты и несогласованные идентификаторы."],["Callbacks","Сопоставляет атрибуты callback с доступным VBA-кодом."]],
    vbaTitle:"Callbacks без ручного копирования", vbaBody:"Для файлов с макросами программа может читать, открывать и сохранять модули VBA, а также создавать отсутствующие сигнатуры callbacks из RibbonX.", vbaSecurity:"Автоматизация VBA требует доступа к объектной модели проекта VBA. Если Office блокирует доступ, редактирование невозможно.",
    imagesTitle:"Встроенные значки и собственные ресурсы", imagesBody:"Галерея imageMso помогает найти правильный идентификатор Office и поддерживает собственные изображения внутри пакета.", previewWord:"Предпросмотр",
    addinsKicker:"Создание", addinsTitle:"Создавайте надстройки Excel, Word и PowerPoint", addinsBody:"Мастер может подготовить файл надстройки, стартовый Ribbon и модуль RibbonCallbacks.", addinUse:"Типичное применение", excelUse:"Инструменты и автоматизация Excel", wordUse:"Шаблоны и инструменты документов", pptUse:"Инструменты презентаций",
    packagingKicker:"Распространение", packagingTitle:"Упаковка надстроек для Windows", packagingBody:"Стабильный рабочий процесс v3.2 использует Inno Setup 6 для сборки Windows-установщика .xlam, .dotm и .ppam.", packagingSafety:"Защита или обфускация выполняется на временной копии, поэтому исходная надстройка не изменяется.",
    comparisonKicker:"Сравнение", comparisonTitle:"Сравнение с существующими инструментами", comparisonBody:"Office RibbonX Editor — специализированный редактор; Visual Studio/VSTO — полноценная среда разработки; исходный Custom UI Editor — устаревший ориентир. Ribbon UI Studio объединяет XML + VBA + надстройку + распространение.", comparisonRows:commonComparison.en, scopeNote:"Это сравнение возможностей, а не рейтинг качества.",
    troubleshootingKicker:"Типичные проблемы", troubleshootingTitle:"Прежде чем считать Ribbon неисправным", troubleshootingCards:[["Callback не запускается","Проверьте имя в XML, формат с макросами и VBA-модуль."],["Office не показывает Ribbon","Проверьте XML, namespace и регистрацию customUI."],["VBA нельзя редактировать","Проверьте Trust Center и используйте доверенные документы."],["Изображение не отображается","Различайте imageMso и пользовательские изображения и проверяйте связи ресурсов."]],
    referenceKicker:"Источники", referenceTitle:"Полезные ссылки", referenceBody:"Сравнение основано на публичной документации проектов и официальной документации Microsoft по VSTO.", projectFeatures:"Проект и возможности", archivedRepo:"Архивированный репозиторий", microsoftRibbon:"Designer и Ribbon XML", releasesSupport:"Версии и поддержка", independent:"Независимое ПО для Microsoft Office. Не связано с Microsoft."
  },
  zh: {
    download:"下载", screenshots:"截图", search:"搜索文档…", noResults:"没有结果", startGroup:"开始", addinsGroup:"加载项", referenceGroup:"参考",
    official:"官方文档 · v3.2", heroTitle:"从 Office 文件到 RibbonX、VBA 和可分发加载项。", heroBody:"实用指南：编辑 customUI XML、管理 VBA 模块、检查回调、使用 imageMso、创建 Excel/Word/PowerPoint 加载项并打包为 Windows 安装程序。", stats:["主要 Office 主程序","RibbonX 架构","XML + VBA + 分发流程"],
    nav:["Ribbon UI Studio 是什么","快速开始","Office 文件与架构","RibbonX XML 编辑器","预览与诊断","VBA 模块与回调","imageMso 与自定义图片","创建 Office 加载项","打包 Windows 安装程序","与现有工具比较","故障排除","参考与外部资源"],
    overviewKicker:"概览", overviewTitle:"Ribbon UI Studio 解决什么问题", overviewBody:"Ribbon UI Studio 是面向 Microsoft Office RibbonX 定制的 Windows 桌面应用。XML、回调、VBA 模块、图标和打包围绕同一个 Office 文件或加载项完成。", overviewCards:[["Office 文件编辑器","直接处理 Open XML 包中的 customUI/customUI14、图片和相关资源，无需手工修改 ZIP。"],["端到端流程","设计 Ribbon、检查回调、编辑 VBA、创建加载项并准备 Windows 安装程序。"]], backup:"修改现有 Office 文档前请始终保留备份。",
    quickKicker:"快速开始", quickTitle:"六步完成第一次定制", quickSteps:[["打开 Office 文件","选择兼容的文档或加载项。"],["创建或打开 customUI","根据需要选择 Office 2007 或 Office 2010+ 架构。"],["编辑 XML","使用 Monaco、标签页、格式化和 RibbonX 模板。"],["验证并预览","在打开 Office 前检查语法、ID、回调和图片。"],["连接 VBA","生成缺失回调并编辑模块。"],["保存并测试","写回 Office 文件并在宿主程序中测试。"]],
    officeKicker:"Office 格式", officeTitle:"Office 2007 与 Office 2010+ 使用不同的 RibbonX 部件", officeBody:"Ribbon UI Studio 能识别两种常见 Open XML 路径，并在需要时创建正确部件。", schema:"架构", path:"路径", macroNote:"要使用 VBA 回调，.xlsx、.docx、.pptx 需先保存为 .xlsm、.docm 或 .pptm。",
    xmlTitle:"像编辑代码一样编辑 XML", xmlBody:"编辑器将 RibbonX XML 与 VBA 模块分开管理，避免保存目标混淆。内置模板可快速建立 Ribbon、动态菜单和图库。", xmlTip:"使用稳定的自定义 ID，并避免重复。",
    previewKicker:"打开 Office 前检查", previewTitle:"可视化预览与诊断", previewBody:"Ribbon UI Studio 无需启动 Office 即可呈现 Ribbon，并解析标签页、组、控件、imageMso、嵌入图片和回调。", previewCards:[["XML","检查 XML 与 namespace。"],["ID","帮助发现重复或不一致的标识符。"],["回调","将回调属性与现有 VBA 代码进行对照。"]],
    vbaTitle:"无需手工复制回调", vbaBody:"对支持宏的文件，程序可以读取、打开、保存 VBA 模块，并根据 RibbonX 生成缺失的回调签名。", vbaSecurity:"VBA 自动化依赖对 VBA 项目对象模型的访问权限。如果 Office 阻止访问，则无法完成模块编辑。",
    imagesTitle:"Office 内置图标与自定义资源", imagesBody:"imageMso 图库可帮助找到正确的 Office 标识符，也支持 Office 包中的自定义图片。", previewWord:"预览",
    addinsKicker:"创建", addinsTitle:"创建 Excel、Word 和 PowerPoint 加载项", addinsBody:"创建流程可准备加载项文件、初始 Ribbon 和 RibbonCallbacks 模块。", addinUse:"典型用途", excelUse:"Excel 工具与自动化", wordUse:"文档模板与工具", pptUse:"演示文稿工具",
    packagingKicker:"分发", packagingTitle:"为 Windows 打包 Office 加载项", packagingBody:"v3.2 的稳定流程使用 Inno Setup 6 编译 .xlam、.dotm 和 .ppam 的 Windows 安装程序。", packagingSafety:"启用保护或混淆时，仅处理临时副本，不修改原始加载项。",
    comparisonKicker:"比较", comparisonTitle:"与现有工具比较", comparisonBody:"Office RibbonX Editor 是专门的 RibbonX 编辑器；Visual Studio/VSTO 是完整开发环境；原始 Custom UI Editor 属于旧版参考。Ribbon UI Studio 试图把 XML + VBA + 加载项 + 分发整合在一起。", comparisonRows:commonComparison.en, scopeNote:"这是功能范围比较，不是质量排名。",
    troubleshootingKicker:"常见问题", troubleshootingTitle:"在判断 Ribbon 出错之前", troubleshootingCards:[["回调未执行","检查 XML 中的名称、宏文件格式和 VBA 模块。"],["Office 未显示 Ribbon","验证 XML、namespace 和 customUI 注册。"],["无法编辑 VBA","检查 Trust Center，并仅使用可信文档。"],["图片未显示","区分 imageMso 与自定义图片，并检查关系和资源。"]],
    referenceKicker:"来源", referenceTitle:"实用参考", referenceBody:"比较基于各项目公开文档和 Microsoft 官方 VSTO 文档。", projectFeatures:"项目与功能", archivedRepo:"已归档仓库", microsoftRibbon:"Designer 与 Ribbon XML", releasesSupport:"版本与支持", independent:"Microsoft Office 独立软件，与 Microsoft 无隶属关系。"
  },
  ja: {
    download:"ダウンロード", screenshots:"スクリーンショット", search:"ドキュメントを検索…", noResults:"結果なし", startGroup:"はじめに", addinsGroup:"アドイン", referenceGroup:"リファレンス",
    official:"公式ドキュメント · v3.2", heroTitle:"Office ファイルから RibbonX、VBA、配布可能なアドインまで。", heroBody:"customUI XML の編集、VBA モジュール、コールバック、imageMso、Excel/Word/PowerPoint アドインの作成、Windows インストーラー化までを説明します。", stats:["主要 Office ホスト","RibbonX スキーマ","XML + VBA + 配布フロー"],
    nav:["Ribbon UI Studio とは","クイックスタート","Office ファイルとスキーマ","RibbonX XML エディター","プレビューと診断","VBA モジュールとコールバック","imageMso とカスタム画像","Office アドインを作成","Windows 用にパッケージ","既存ツールとの比較","トラブルシューティング","参考資料"],
    overviewKicker:"概要", overviewTitle:"Ribbon UI Studio が解決すること", overviewBody:"Ribbon UI Studio は Microsoft Office の RibbonX カスタマイズ向け Windows デスクトップアプリです。XML、コールバック、VBA モジュール、アイコン、パッケージングを同じ Office ファイルやアドインを中心に扱えます。", overviewCards:[["Office ファイルエディター","ZIP を手作業で編集せず、Open XML パッケージ内の customUI/customUI14、画像、関連リソースを扱えます。"],["一貫したワークフロー","Ribbon 設計、コールバック確認、VBA 編集、アドイン作成、Windows インストーラー作成まで行えます。"]], backup:"既存の Office 文書を変更する前に必ずバックアップしてください。",
    quickKicker:"クイックスタート", quickTitle:"最初のカスタマイズを 6 ステップで", quickSteps:[["Office ファイルを開く","対応する文書またはアドインを選びます。"],["customUI を作成または開く","Office 2007 または Office 2010+ を選びます。"],["XML を編集","Monaco、タブ、整形、RibbonX テンプレートを使います。"],["検証とプレビュー","構文、ID、コールバック、画像を確認します。"],["VBA を接続","不足コールバックを生成し、モジュールを編集します。"],["保存してテスト","Office ファイルに保存し、ホストアプリで確認します。"]],
    officeKicker:"Office 形式", officeTitle:"Office 2007 と Office 2010+ は異なる RibbonX パーツを使用します", officeBody:"Ribbon UI Studio は一般的な 2 つの Open XML パスを認識し、必要なパーツを作成できます。", schema:"スキーマ", path:"パス", macroNote:"VBA コールバックを使う場合、.xlsx/.docx/.pptx は .xlsm/.docm/.pptm に保存し直してください。",
    xmlTitle:"XML をコードとして編集", xmlBody:"RibbonX XML と VBA モジュールを別ドキュメントとして管理し、保存先の混同を防ぎます。テンプレートで Ribbon、動的メニュー、ギャラリーをすばやく作れます。", xmlTip:"安定した独自 ID を使い、重複を避けてください。",
    previewKicker:"Office を開く前に確認", previewTitle:"ビジュアルプレビューと診断", previewBody:"Office を起動せずに Ribbon を表現し、タブ、グループ、コントロール、imageMso、埋め込み画像、コールバックを確認できます。", previewCards:[["XML","XML と namespace を確認します。"],["ID","重複または不整合な ID の検出を支援します。"],["Callbacks","コールバック属性と VBA コードを照合します。"]],
    vbaTitle:"コールバックを手作業でコピーする必要はありません", vbaBody:"マクロ対応ファイルでは VBA モジュールを読み書きし、RibbonX から不足するコールバック署名を生成できます。", vbaSecurity:"VBA 自動化には VBA プロジェクトオブジェクトモデルへのアクセス許可が必要です。Office がブロックすると編集できません。",
    imagesTitle:"組み込みアイコンとカスタムリソース", imagesBody:"imageMso ギャラリーで正しい Office ID を探し、Office パッケージ内のカスタム画像も扱えます。", previewWord:"プレビュー",
    addinsKicker:"作成", addinsTitle:"Excel、Word、PowerPoint アドインを作成", addinsBody:"アドインファイル、初期 Ribbon、RibbonCallbacks モジュールを準備できます。", addinUse:"主な用途", excelUse:"Excel ツールと自動化", wordUse:"文書テンプレートとツール", pptUse:"プレゼンテーションツール",
    packagingKicker:"配布", packagingTitle:"Office アドインを Windows 用にパッケージ", packagingBody:"v3.2 の安定したフローでは Inno Setup 6 を使用して .xlam/.dotm/.ppam の Windows インストーラーを生成します。", packagingSafety:"保護や難読化は一時コピー上で行われ、元のアドインは変更されません。",
    comparisonKicker:"比較", comparisonTitle:"既存ツールとの比較", comparisonBody:"Office RibbonX Editor は専用エディター、Visual Studio/VSTO は総合開発環境、元の Custom UI Editor は旧来の参照ツールです。Ribbon UI Studio は XML + VBA + アドイン + 配布をまとめます。", comparisonRows:commonComparison.en, scopeNote:"機能範囲の比較であり、品質ランキングではありません。",
    troubleshootingKicker:"よくある問題", troubleshootingTitle:"Ribbon の故障と判断する前に", troubleshootingCards:[["コールバックが動作しない","XML 名、マクロ対応形式、VBA モジュールを確認します。"],["Office に Ribbon が表示されない","XML、namespace、customUI 登録を確認します。"],["VBA を編集できない","Trust Center を確認し、信頼できる文書を使います。"],["画像が表示されない","imageMso とカスタム画像を区別し、関係とリソースを確認します。"]],
    referenceKicker:"情報源", referenceTitle:"参考リンク", referenceBody:"比較は各プロジェクトの公開資料と Microsoft の公式 VSTO ドキュメントに基づきます。", projectFeatures:"プロジェクトと機能", archivedRepo:"アーカイブ済みリポジトリ", microsoftRibbon:"Designer と Ribbon XML", releasesSupport:"リリースとサポート", independent:"Microsoft Office 向け独立ソフトウェアです。Microsoft とは提携していません。"
  },
  hi: {
    download:"डाउनलोड", screenshots:"स्क्रीनशॉट", search:"दस्तावेज़ खोजें…", noResults:"कोई परिणाम नहीं", startGroup:"यहाँ से शुरू करें", addinsGroup:"ऐड-इन्स", referenceGroup:"संदर्भ",
    official:"आधिकारिक दस्तावेज़ · v3.2", heroTitle:"Office फ़ाइल से RibbonX, VBA और वितरित किए जा सकने वाले ऐड-इन तक।", heroBody:"customUI XML संपादन, VBA मॉड्यूल, callbacks, imageMso, Excel/Word/PowerPoint ऐड-इन बनाना और Windows के लिए पैकेज करना — एक व्यावहारिक मार्गदर्शिका।", stats:["मुख्य Office hosts","RibbonX schemas","XML + VBA + वितरण workflow"],
    nav:["Ribbon UI Studio क्या है","त्वरित शुरुआत","Office फ़ाइलें और schemas","RibbonX XML editor","Preview और diagnostics","VBA modules और callbacks","imageMso और custom images","Office add-ins बनाएँ","Windows के लिए package करें","मौजूदा tools से तुलना","समस्या निवारण","संदर्भ और संसाधन"],
    overviewKicker:"परिचय", overviewTitle:"Ribbon UI Studio किस समस्या को हल करता है", overviewBody:"Ribbon UI Studio Microsoft Office RibbonX customization पर केंद्रित Windows desktop application है। XML, callbacks, VBA modules, icons और packaging को एक ही Office document या add-in के आसपास रखा जाता है।", overviewCards:[["Office file editor","ZIP को manually edit किए बिना Open XML package में customUI/customUI14, images और related content पर काम करें।"],["End-to-end workflow","Ribbon design करें, callbacks जाँचें, VBA edit करें, add-in बनाएँ और Windows installer तैयार करें।"]], backup:"किसी मौजूदा Office document को बदलने से पहले हमेशा backup रखें।",
    quickKicker:"त्वरित शुरुआत", quickTitle:"छह चरणों में पहली customization", quickSteps:[["Office फ़ाइल खोलें","Compatible document या add-in चुनें।"],["customUI बनाएँ या खोलें","Office 2007 या Office 2010+ schema चुनें।"],["XML edit करें","Monaco, tabs, formatting और RibbonX templates का उपयोग करें।"],["Validate और preview करें","Syntax, IDs, callbacks और images जाँचें।"],["VBA जोड़ें","Missing callbacks generate करें और modules edit करें।"],["Save और test करें","Office फ़ाइल में save करें और host application में test करें।"]],
    officeKicker:"Office format", officeTitle:"Office 2007 और Office 2010+ अलग RibbonX parts उपयोग करते हैं", officeBody:"Ribbon UI Studio दोनों सामान्य Open XML locations पहचानता है और सही part बना सकता है।", schema:"Schema", path:"Path", macroNote:"VBA callbacks के लिए .xlsx, .docx और .pptx को पहले .xlsm, .docm या .pptm में save करें।",
    xmlTitle:"XML को code की तरह edit करें", xmlBody:"Editor RibbonX XML और VBA modules को अलग documents में रखता है, जिससे save targets नहीं मिलते। Built-in templates common ribbons, dynamic menus और galleries के लिए उपयोगी हैं।", xmlTip:"Stable custom IDs उपयोग करें और duplicates से बचें।",
    previewKicker:"Office से पहले जाँच", previewTitle:"Visual preview और diagnostics", previewBody:"Ribbon UI Studio Office खोले बिना Ribbon representation बना सकता है और tabs, groups, controls, imageMso, embedded images और callbacks को interpret करता है।", previewCards:[["XML","Valid XML और expected namespace जाँचता है।"],["IDs","Duplicate या inconsistent identifiers खोजने में मदद करता है।"],["Callbacks","Callback attributes को उपलब्ध VBA code से मिलाता है।"]],
    vbaTitle:"Callbacks को manually copy करने की जरूरत नहीं", vbaBody:"Macro-enabled files में Ribbon UI Studio VBA modules पढ़, खोल और save कर सकता है तथा RibbonX से missing callback signatures बना सकता है।", vbaSecurity:"VBA automation के लिए VBA project object model access आवश्यक है। Office इसे block करे तो module editing पूरी नहीं होगी।",
    imagesTitle:"Built-in icons और custom resources", imagesBody:"imageMso gallery सही Office identifier खोजने में मदद करती है और Office package में custom images के साथ भी काम करती है।", previewWord:"Preview",
    addinsKicker:"Creation", addinsTitle:"Excel, Word और PowerPoint add-ins बनाएँ", addinsBody:"Workflow add-in file, starter Ribbon और RibbonCallbacks module तैयार कर सकता है।", addinUse:"Typical use", excelUse:"Excel tools और automation", wordUse:"Document templates और tools", pptUse:"Presentation tools",
    packagingKicker:"Distribution", packagingTitle:"Office add-ins को Windows के लिए package करें", packagingBody:"v3.2 का stable workflow .xlam, .dotm और .ppam के Windows installer को compile करने के लिए Inno Setup 6 उपयोग करता है।", packagingSafety:"Protection या obfuscation temporary copy पर चलता है, इसलिए original add-in नहीं बदलता।",
    comparisonKicker:"तुलना", comparisonTitle:"मौजूदा tools से तुलना", comparisonBody:"Office RibbonX Editor एक focused editor है; Visual Studio/VSTO full development environment है; original Custom UI Editor legacy reference है। Ribbon UI Studio XML + VBA + add-in + distribution को साथ लाता है।", comparisonRows:commonComparison.en, scopeNote:"यह scope comparison है, quality ranking नहीं।",
    troubleshootingKicker:"सामान्य समस्याएँ", troubleshootingTitle:"Ribbon को खराब मानने से पहले", troubleshootingCards:[["Callback नहीं चलता","XML name, macro-enabled format और VBA module जाँचें।"],["Office Ribbon नहीं दिखाता","XML, namespace और customUI registration जाँचें।"],["VBA edit नहीं होता","Trust Center settings जाँचें और trusted documents उपयोग करें।"],["Image नहीं दिखती","imageMso और custom images में अंतर करें तथा relationships/resources जाँचें।"]],
    referenceKicker:"स्रोत", referenceTitle:"उपयोगी संदर्भ", referenceBody:"तुलना project documentation और Microsoft की official VSTO documentation पर आधारित है।", projectFeatures:"Project और features", archivedRepo:"Archived repository", microsoftRibbon:"Designer और Ribbon XML", releasesSupport:"Releases और support", independent:"Microsoft Office के लिए स्वतंत्र software. Microsoft से संबद्ध नहीं।"
  }
};
